// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package mocks

import (
	"context"
	"sync"
)

// SubscriptionStoreMock is a mock implementation of rest.SubscriptionStore.
//
//	func TestSomethingThatUsesSubscriptionStore(t *testing.T) {
//
//		// make and configure a mocked rest.SubscriptionStore
//		mockedSubscriptionStore := &SubscriptionStoreMock{
//			AddSubscriptionFunc: func(ctx context.Context, addr string) error {
//				panic("mock out the AddSubscription method")
//			},
//			GetSubscriptionsFunc: func(ctx context.Context) ([]string, error) {
//				panic("mock out the GetSubscriptions method")
//			},
//			IsSubscribedFunc: func(ctx context.Context, addr string) (bool, error) {
//				panic("mock out the IsSubscribed method")
//			},
//		}
//
//		// use mockedSubscriptionStore in code that requires rest.SubscriptionStore
//		// and then make assertions.
//
//	}
type SubscriptionStoreMock struct {
	// AddSubscriptionFunc mocks the AddSubscription method.
	AddSubscriptionFunc func(ctx context.Context, addr string) error

	// GetSubscriptionsFunc mocks the GetSubscriptions method.
	GetSubscriptionsFunc func(ctx context.Context) ([]string, error)

	// IsSubscribedFunc mocks the IsSubscribed method.
	IsSubscribedFunc func(ctx context.Context, addr string) (bool, error)

	// calls tracks calls to the methods.
	calls struct {
		// AddSubscription holds details about calls to the AddSubscription method.
		AddSubscription []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Addr is the addr argument value.
			Addr string
		}
		// GetSubscriptions holds details about calls to the GetSubscriptions method.
		GetSubscriptions []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
		}
		// IsSubscribed holds details about calls to the IsSubscribed method.
		IsSubscribed []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Addr is the addr argument value.
			Addr string
		}
	}
	lockAddSubscription  sync.RWMutex
	lockGetSubscriptions sync.RWMutex
	lockIsSubscribed     sync.RWMutex
}

// AddSubscription calls AddSubscriptionFunc.
func (mock *SubscriptionStoreMock) AddSubscription(ctx context.Context, addr string) error {
	if mock.AddSubscriptionFunc == nil {
		panic("SubscriptionStoreMock.AddSubscriptionFunc: method is nil but SubscriptionStore.AddSubscription was just called")
	}
	callInfo := struct {
		Ctx  context.Context
		Addr string
	}{
		Ctx:  ctx,
		Addr: addr,
	}
	mock.lockAddSubscription.Lock()
	mock.calls.AddSubscription = append(mock.calls.AddSubscription, callInfo)
	mock.lockAddSubscription.Unlock()
	return mock.AddSubscriptionFunc(ctx, addr)
}

// AddSubscriptionCalls gets all the calls that were made to AddSubscription.
// Check the length with:
//
//	len(mockedSubscriptionStore.AddSubscriptionCalls())
func (mock *SubscriptionStoreMock) AddSubscriptionCalls() []struct {
	Ctx  context.Context
	Addr string
} {
	var calls []struct {
		Ctx  context.Context
		Addr string
	}
	mock.lockAddSubscription.RLock()
	calls = mock.calls.AddSubscription
	mock.lockAddSubscription.RUnlock()
	return calls
}

// GetSubscriptions calls GetSubscriptionsFunc.
func (mock *SubscriptionStoreMock) GetSubscriptions(ctx context.Context) ([]string, error) {
	if mock.GetSubscriptionsFunc == nil {
		panic("SubscriptionStoreMock.GetSubscriptionsFunc: method is nil but SubscriptionStore.GetSubscriptions was just called")
	}
	callInfo := struct {
		Ctx context.Context
	}{
		Ctx: ctx,
	}
	mock.lockGetSubscriptions.Lock()
	mock.calls.GetSubscriptions = append(mock.calls.GetSubscriptions, callInfo)
	mock.lockGetSubscriptions.Unlock()
	return mock.GetSubscriptionsFunc(ctx)
}

// GetSubscriptionsCalls gets all the calls that were made to GetSubscriptions.
// Check the length with:
//
//	len(mockedSubscriptionStore.GetSubscriptionsCalls())
func (mock *SubscriptionStoreMock) GetSubscriptionsCalls() []struct {
	Ctx context.Context
} {
	var calls []struct {
		Ctx context.Context
	}
	mock.lockGetSubscriptions.RLock()
	calls = mock.calls.GetSubscriptions
	mock.lockGetSubscriptions.RUnlock()
	return calls
}

// IsSubscribed calls IsSubscribedFunc.
func (mock *SubscriptionStoreMock) IsSubscribed(ctx context.Context, addr string) (bool, error) {
	if mock.IsSubscribedFunc == nil {
		panic("SubscriptionStoreMock.IsSubscribedFunc: method is nil but SubscriptionStore.IsSubscribed was just called")
	}
	callInfo := struct {
		Ctx  context.Context
		Addr string
	}{
		Ctx:  ctx,
		Addr: addr,
	}
	mock.lockIsSubscribed.Lock()
	mock.calls.IsSubscribed = append(mock.calls.IsSubscribed, callInfo)
	mock.lockIsSubscribed.Unlock()
	return mock.IsSubscribedFunc(ctx, addr)
}

// IsSubscribedCalls gets all the calls that were made to IsSubscribed.
// Check the length with:
//
//	len(mockedSubscriptionStore.IsSubscribedCalls())
func (mock *SubscriptionStoreMock) IsSubscribedCalls() []struct {
	Ctx  context.Context
	Addr string
} {
	var calls []struct {
		Ctx  context.Context
		Addr string
	}
	mock.lockIsSubscribed.RLock()
	calls = mock.calls.IsSubscribed
	mock.lockIsSubscribed.RUnlock()
	return calls
}
